twitter_key: <%= Rails.application.credentials.twitter_key %>
twitter_secret: <%= Rails.application.credentials.twitter_secret %>
twitter_callback_url: <%= Rails.application.credentials.twitter_callback_url %>
